name: CI

on: [push]

jobs: 
  build:
    if: "!contains(github.event.head_commit.message,'[skip sky]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build
        run: echo "Running the build..."
